Strategy(fill column&print column)
kimiares/FileManager pull request #12
Opened 2022-01-14 06:58 UTC by kimiares

Added Set Content/Print Content methods

2022-01-19 11:17 UTC, Retro-kharkov1 requested changes

2022-01-19 11:17 UTC, Retro-kharkov1 commented on FileManager/Program.cs
> +                testFSI);
63-64 отступ

2022-01-19 11:17 UTC, Retro-kharkov1 commented on FileManager/Program.cs
> +            ICheckArea panel1 = new Panel(
сделать класс ModelPanel и все поместить там

2022-01-19 11:17 UTC, Retro-kharkov1 commented on FileManager/Structure/Panel.cs
> +                        new Point(mySet.Sets.ALX + 1 - i + i * mySet.ColumnWidthLeft + this.Index*(mySet.Sets.PanelWidth+1), mySet.Sets.ALY + 1),
что это?

2022-01-19 11:17 UTC, Retro-kharkov1 commented on FileManager/Structure/Panel.cs
> +                        new Point(mySet.Sets.ALX + 1 - i + i * mySet.ColumnWidthLeft + this.Index*(mySet.Sets.PanelWidth+1), mySet.Sets.ALY + 1),
вынести в функцию расчеты

2022-01-19 11:17 UTC, Retro-kharkov1 commented on FileManager/Structure/PanelStrategy/EachColumn.cs
> +        public void SetContent(List<Column> columns, List<FileSystemInfo> input)
красивее сделать через this и вернуть лист колонок

2022-01-19 11:17 UTC, Retro-kharkov1 commented on FileManager/Structure/PanelStrategy/EachColumn.cs
> +        public void CheckColumn(int index, FileSystemInfo file)
когда функция начинаеться с check, has, is она должна вернуть true или false

2022-01-20 11:49 UTC, kimiares commented on FileManager/Structure/PanelStrategy/EachColumn.cs
> +        public void CheckColumn(int index, FileSystemInfo file)
метода уже нет

2022-01-21 12:18 UTC, kimiares commented on FileManager/Program.cs
> +                testFSI);
добавил

2022-01-21 12:52 UTC, kimiares commented on FileManager/Program.cs
> +            ICheckArea panel1 = new Panel(
добавил

2022-01-21 12:58 UTC, kimiares commented on FileManager/Structure/Panel.cs
> +                        new Point(mySet.Sets.ALX + 1 - i + i * mySet.ColumnWidthLeft + this.Index*(mySet.Sets.PanelWidth+1), mySet.Sets.ALY + 1),
вынес

2022-01-21 13:00 UTC, kimiares commented on FileManager/Structure/PanelStrategy/EachColumn.cs
> +        public void SetContent(List<Column> columns, List<FileSystemInfo> input)
метод уже переписан в новых пулах

2022-01-21 15:48 UTC, Retro-kharkov1 approved these changes

2022-01-21 15:58 UTC, merged