Parent directory on top
kimiares/FileManager pull request #13
Opened 2022-01-14 15:03 UTC by kimiares

First pull for review:
https://github.com/kimiares/FileManager/pull/12

- Added parent directory for each column(or for the first, if it option was chosen)
- Print ".." at the first row of column

2022-01-19 12:01 UTC, Retro-kharkov1 requested changes

2022-01-19 12:01 UTC, Retro-kharkov1 commented on FileManager/Program.cs
> +            Buttons F_Buttons = new Buttons(new Drawing.Point(1, 29), 10, 1, 2, items);
а че не 42 цифра, я любою 42, она отвечатет на вопрос в чем смысл жизни и все такое...
в константы вынести!!

2022-01-19 12:01 UTC, Retro-kharkov1 commented on FileManager/Structure/PanelStrategy/EachColumn.cs
>      public class EachColumn : IPanelStrategy
а почему EachColumn а не Column например

2022-01-19 12:01 UTC, Retro-kharkov1 commented on FileManager/Structure/PanelStrategy/EachColumn.cs
> +            if (index == 1)
что это?

2022-01-19 12:01 UTC, Retro-kharkov1 commented on FileManager/Structure/PanelStrategy/EachColumn.cs
> +            if (index == 2)
и это что?

2022-01-19 12:01 UTC, Retro-kharkov1 commented on FileManager/Structure/PanelStrategy/EachColumn.cs
> +        public static string CheckColumn(int index, FileSystemInfo file)
наверно это gettext ?

2022-01-19 12:01 UTC, Retro-kharkov1 commented on FileManager/Structure/PanelStrategy/SupportMethods.cs
> +    class SupportMethods
pablic!!!!

2022-01-19 12:01 UTC, Retro-kharkov1 commented on FileManager/Structure/PanelStrategy/SupportMethods.cs
> +        public static string CutName(string name)
он тока имена обрезает !?!? CutString
и сделай его экстеншеном через this

2022-01-20 08:09 UTC, kimiares commented on FileManager/Structure/PanelStrategy/SupportMethods.cs
> +        public static string CutName(string name)
Сделал(хоть это и устаревший вариант, но исправил нейминг в экстеншине)

2022-01-21 13:07 UTC, kimiares commented on FileManager/Structure/PanelStrategy/EachColumn.cs
>      public class EachColumn : IPanelStrategy
Нейминг поправил

2022-01-21 13:07 UTC, kimiares commented on FileManager/Structure/PanelStrategy/EachColumn.cs
> +            if (index == 1)
Метод отсутсвует в следующих пуллах

2022-01-21 13:07 UTC, kimiares commented on FileManager/Structure/PanelStrategy/SupportMethods.cs
> +    class SupportMethods
added

2022-01-21 13:17 UTC, kimiares commented on FileManager/Program.cs
> +            Buttons F_Buttons = new Buttons(new Drawing.Point(1, 29), 10, 1, 2, items);
вынесено в константы/конфигурацию

2022-01-21 15:57 UTC, Retro-kharkov1 approved these changes

2022-01-21 16:35 UTC, merged