Set sells columns
kimiares/FileManager pull request #14
Opened 2022-01-17 08:11 UTC by kimiares

Look at https://github.com/kimiares/FileManager/pull/13 first pls
Changed Cells creating.
(now cells create before the filling columns )

2022-01-19 12:22 UTC, Retro-kharkov1 requested changes

2022-01-19 12:22 UTC, Retro-kharkov1 commented on FileManager/Program.cs
> +                new AllColumn(),
AllColumns  - тогда

2022-01-19 12:22 UTC, Retro-kharkov1 commented on FileManager/Program.cs
> +                new EachColumn(),
я не понял в чем разница тут EachColumns там AllColumns

2022-01-19 12:22 UTC, Retro-kharkov1 commented on FileManager/Structure/Extentions/Enumerable.cs
> +        private static Exception ArgumentNullException(string v)
не не, сой эксепшен это отдельный класс наследованный от нужного тебе экспешена и ложи их в свою папку с эксепшенами

2022-01-19 12:22 UTC, Retro-kharkov1 commented on FileManager/Structure/Extentions/Enumerable.cs
> +        private static Exception ArgumentNullException(string v)
во вторых у тебя класс отвечает за работу с коллекцияими но не с эксепшенами

2022-01-19 12:22 UTC, Retro-kharkov1 commented on FileManager/Structure/Extentions/SupportMethods.cs
> +            Console.WriteLine(data.CutName());
методы где одна строка лучше пиши через лямду читабеленй будет

```
 public static void Write(this string data)=>
    Console.WriteLine(data.CutName());
```

2022-01-19 12:22 UTC, Retro-kharkov1 commented on FileManager/Structure/PanelStrategy/ParentDirectory.cs
> +        public ParentDirectory(string fullPath)
метод который вычленяет парент директори елси ты его не исопльзуешь больше нигде кроме для этого случая, то лучше написать внутри этого класс и исопльзывать в конструкторе

2022-01-20 08:07 UTC, kimiares commented on FileManager/Structure/Extentions/Enumerable.cs
> +        private static Exception ArgumentNullException(string v)
создал папку, пихаю туда свои эксепшены

2022-01-20 08:07 UTC, kimiares commented on FileManager/Program.cs
> +                new EachColumn(),
Изменил нейминг

2022-01-20 08:08 UTC, kimiares commented on FileManager/Structure/PanelStrategy/ParentDirectory.cs
> +        public ParentDirectory(string fullPath)
поправил, выглядит классно

2022-01-21 13:23 UTC, kimiares commented on FileManager/Structure/Extentions/SupportMethods.cs
> +            Console.WriteLine(data.CutName());
изменил

2022-01-21 13:35 UTC, kimiares commented on FileManager/Program.cs
> +                new AllColumn(),
нейминг изменил

2022-01-21 15:56 UTC, Retro-kharkov1 approved these changes

2022-01-21 15:56 UTC, Retro-kharkov1 commented on FileManager/Operations/Net.cs
> +    public class Net: IOperation
чет то мне кажеться ветка не сбилдиться

2022-01-21 17:09 UTC, merged