Navigation list
kimiares/FileManager pull request #15
Opened 2022-01-19 10:56 UTC by YuriiDDD

1. First review of navigation
https://github.com/kimiares/FileManager/tree/Set-sells-columns

2022-01-19 12:29 UTC, Retro-kharkov1 requested changes

2022-01-19 12:29 UTC, Retro-kharkov1 commented on FileManager/Program.cs
> +                else if (MyKey.Key == ConsoleKey.DownArrow)
else if испольузем если совсем без выходная ситуаци, тут  лучше либо swicth case, 
а еще лучше dictionary и вынести в статик переменнную

2022-01-19 12:29 UTC, Retro-kharkov1 commented on FileManager/Structure/Panel.cs
>          public void Set()
у тебя в методе Set -> RefreshContent и PrintContent  - кажетсья метод назван не корректно

2022-01-19 12:29 UTC, Retro-kharkov1 commented on FileManager/Structure/Panel.cs
> +        public void RefreshContent()
так это не RefreshContent а CleanPanel

2022-01-19 12:29 UTC, Retro-kharkov1 commented on FileManager/Structure/Panel.cs
> +            if ((newIndex < 27)&(oldIndex<27))
что такое 27? почему не 42?

2022-01-19 12:29 UTC, Retro-kharkov1 commented on FileManager/Structure/PanelStrategy/EachColumn.cs
> +            cells = cells.Take(mySet.MaxElementsColumn).ToList();
в одну стрку с SetContent и к ToList не приводи

2022-01-19 18:14 UTC, YuriiDDD commented on FileManager/Structure/PanelStrategy/EachColumn.cs
> +            cells = cells.Take(mySet.MaxElementsColumn).ToList();
Исправил

2022-01-19 18:15 UTC, YuriiDDD commented on FileManager/Structure/Panel.cs
> +            if ((newIndex < 27)&(oldIndex<27))
Тоже исправил

2022-01-19 18:15 UTC, YuriiDDD commented on FileManager/Structure/Panel.cs
> +        public void RefreshContent()
Переназвал

2022-01-19 18:15 UTC, YuriiDDD commented on FileManager/Structure/Panel.cs
>          public void Set()
Тоже переназвал

2022-01-19 18:16 UTC, YuriiDDD commented on FileManager/Program.cs
> +                else if (MyKey.Key == ConsoleKey.DownArrow)
Пока заменил на switch, case.

2022-01-21 16:01 UTC, Retro-kharkov1 requested changes

2022-01-21 16:01 UTC, Retro-kharkov1 commented on FileManager/Program.cs
> +            PanelModel firstPanelModel = new PanelModel();
; в конце не нужна

2022-01-21 16:01 UTC, Retro-kharkov1 commented on FileManager/Program.cs
> +                firstPanelModel.FinishPoint = new Point(59, 27);
firstPanelModel удалить оставить только название свойств

2022-01-21 16:01 UTC, Retro-kharkov1 commented on FileManager/Program.cs
> +                        ddd.FillPanel();
заметил `ddd.FillPanel();` повторяеться?
вынести за switch

2022-01-21 16:01 UTC, Retro-kharkov1 commented on FileManager/Program.cs
> +            Panel ddd = panel;
не понял смысла манипуляции. Масло маслянное

2022-01-21 16:16 UTC, YuriiDDD commented on FileManager/Program.cs
> +            PanelModel firstPanelModel = new PanelModel();
исправил

2022-01-21 16:17 UTC, YuriiDDD commented on FileManager/Program.cs
> +                firstPanelModel.FinishPoint = new Point(59, 27);
убрал firstPanelModel

2022-01-21 16:17 UTC, YuriiDDD commented on FileManager/Program.cs
> +                        ddd.FillPanel();
исправил

2022-01-21 16:23 UTC, YuriiDDD commented on FileManager/Program.cs
> +            Panel ddd = panel;
берем названия кнопок, помещаем их в лист, при необходимости расширяем до 10 символов

2022-01-21 17:01 UTC, Retro-kharkov1 requested changes

2022-01-21 17:01 UTC, Retro-kharkov1 commented on FileManager/Structure/PanelStrategy/ThreeProperties.cs
> +        public IEnumerable<Cell> SetContent(Panel panel, List<FileSystemInfo> input)
чем отлечаеться этот метод от метода
https://github.com/kimiares/FileManager/pull/15/files#diff-2206a490f7f610503e40c655d5389642d125555208f11ccea5a6c089d7780295R18

2022-01-21 17:01 UTC, Retro-kharkov1 commented on FileManager/Structure/Extentions/Enumerable.cs
> +        static IEnumerable<TResult> ZipAllIterator<TFirst, TSecond, TResult>(IEnumerable<TFirst> first,
между любыми методами пробел в одну строку

2022-01-21 17:18 UTC, YuriiDDD commented on FileManager/Structure/PanelStrategy/ThreeProperties.cs
> +        public IEnumerable<Cell> SetContent(Panel panel, List<FileSystemInfo> input)
ничем не отличаются

2022-01-21 17:19 UTC, YuriiDDD commented on FileManager/Structure/Extentions/Enumerable.cs
> +        static IEnumerable<TResult> ZipAllIterator<TFirst, TSecond, TResult>(IEnumerable<TFirst> first,
исправил

2022-01-24 11:48 UTC, Retro-kharkov1 approved these changes

2022-01-24 12:01 UTC, merged